### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Bilbo77-Instagram-Feed-con-Bootstrap#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @Bilbo77. ¡Felicidades! :clap:
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Muy buen trabajo utilizando únicamente las clases de bootstrap sin añadir un `styles.css`
- Atento a la apertura y cierre de las etiquetas. Este `<ul>` no tiene cierre 
![Captura de pantalla de 2024-03-11 17-35-26](https://github.com/4GeeksAcademy/Bilbo77-Instagram-Feed-con-Bootstrap/assets/139759297/d7ada5a8-654b-48be-9f00-9c23076cb5eb)
- La clase pd-2 no existe en boostrap 
![Captura de pantalla de 2024-03-11 17-39-17](https://github.com/4GeeksAcademy/Bilbo77-Instagram-Feed-con-Bootstrap/assets/139759297/b910f33f-20af-4fdd-922d-d54e45baea24)
- Tienes etiquetas redundantes 
![Captura de pantalla de 2024-03-11 17-40-34](https://github.com/4GeeksAcademy/Bilbo77-Instagram-Feed-con-Bootstrap/assets/139759297/1c99ec51-2f4b-41f2-abe0-20be6c1907c0)

Fíjate en el número de las líneas de código (19, 40 y 133) que te he enlazado para que puedas revisarlo.

**Comment by Bilbo77** [comment]
El cierre o la redundancia de etiquetas se debe a haber trabajado cansado y de forma desorganizada, tomo nota para la próxima. La clase "pd" en realidad es "p de padding" pero mi cerebro siempre lo interpreta como pd y luego tengo que corregirlo a p, no sé porqué se me ha grabado así, despiste mío.

**Comment by EduardoHernandezGuzman** [comment]
Buen trabajo!!!
